# Generated by Django 4.1.6 on 2023-03-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='sId',
        ),
    ]
